version: '3'
services:
 mongo:
  ports:
   - 127.0.0.1:27017:27017
  environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=password
  container_name: mongo1
  networks:
   - my-mongo-cluster
  image: mongo:7
  command: --replSet myReplicaSet --bind_ip_all --keyFile '/keyfile'
  healthcheck:
   test:
    [
     'CMD-SHELL',
     "mongosh --username root --password password --authenticationDatabase admin --eval 'try { rs.status() } catch (err) { rs.initiate() }' || exit 1",
    ]
   interval: 30s
   timeout: 10s
   retries: 5
   start_period: 30s

volumes:
 mongodb-data:
  driver: local
  name: mongo-data
 mongodb-log:
  driver: local
  name: mongo-log

networks:
 my-mongo-cluster:
  external: true
  driver: bridge
  name: my-mongo-cluster
